title: 48-734<br> Possibilistic Design
description: Course site
theme: just-the-docs

url: https://sinangoral.github.io/possibilistic-design/
  
# Aux links for the upper right navigation
aux_links:
  "View in GitHub ↗":
    - "//github.com/sinangoral/possibilistic-design"
    
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

nav_external_links:
  - title: Syllabus
    url: https://github.com/just-the-docs/just-the-docs
    nav_order: 2
    hide_icon: false # set to true to hide the external link icon - defaults to false
  - title: Schedule
    url: https://github.com/just-the-docs/just-the-docs
    nav_order: 3
    hide_icon: false # set to true to hide the external link icon - defaults to false

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
      
# Footer content
# appears at the bottom of every page's main content
footer_content:
  <a href="https://www.sinangoral.com/">Sinan Goral</a> <br>
  Carnegie Mellon University <br>
  Integrative Design, Arts, and Technology <a href="https://ideate.cmu.edu/index.html">(IDeATe)</a> <br>
  <br>
  48-734 • Possibilistic Design • Fall 2023 <br>
  All rights reserved. Copyright &copy; 2023
